server {
    listen 443 ssl;
    server_name _;
    ssl_certificate /etc/instruct/certs/fullchain.pem;
    ssl_certificate_key /etc/instruct/certs/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    client_max_body_size 51m;
    add_header Strict-Transport-Security "max-age=31536000" always;
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_read_timeout 300s;
    }
}
